name: "check"

on:
  schedule:
    - cron: 5/5 * * * *
  workflow_dispatch:

jobs:
  run-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get previous workflow status
        uses: Mercymeilya/last-workflow-status@v0.3.2
        id: before
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('package.json', 'yarn.lock') }}
          restore-keys: |
            node_modules-

      - name: Install dependencies
        shell: bash
        run: |
          set -ex
          yarn --frozen-lockfile --non-interactive

      - name: Run check
        shell: bash
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          CHANNEL: ${{ secrets.CHANNEL }}
        run: |
          yarn start

      - name: Discord notification
        if: "${{ success() && steps.before.outputs.last_status == 'failure' }}"
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: |
            ${{ secrets.CHANNEL }} has gone live on Twitch!
            https://twitch.tv/${{ secrets.CHANNEL }}

      - name: Discord notification
        if: "${{ failure() && steps.before.outputs.last_status != 'failure' }}"
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: |
            ${{ secrets.CHANNEL }} is now offline.